# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Demo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]



jobs:  
    
  call-codeql:
     uses: sohel-samm/codeql_repo/.github/workflows/codeql.yml@main 
     permissions:                # 👈 must declare here
      security-events: write    # allow uploading results
      contents: read  
      actions: read
      packages: read

  call-rdp:
    needs: call-codeql
    uses: sohel-samm/codeql_repo/.github/workflows/rdp.yml@main
    permissions:
      contents: read
      actions: read
      packages: read
      

   
